version: '3'

services:
  seq:
    image: datalust/seq
    container_name: seq_l
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5342:80

  prometheus:
    image: prom/prometheus
    ports:
      - 8888:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    ports:
      - 4000:3000
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning