apiversion: 1

datasources:
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://localhost:9090"
    org_id: 1
    password:
    user:
    database:
    basicAuth: false
    isDefault: true
    jsonData:
    readOnly: false
